import './globals.css';
import type { Metadata } from 'next';
import Header from './components/layout/navbar';
import Footer from './components/layout/footer';

export const metadata: Metadata = {
  title: 'Storo Grill',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
